modLoader = "javafml" #mandatory
loaderVersion = "[51.0.0,60.0.0)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "ARR" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/sjavi4/ElytraMaceSmasher/issues" #optional
clientSideOnly=true #optional
#LETS PUT THIS ON CLIENT SIDE FOR MODERN FORGE.
displayTest="IGNORE_SERVER_VERSION"

[[mods]] #mandatory
modId = "elytramace" #mandatory
version = "1.0-FOR-1.21.10" #mandatory
displayName = "ElytraMace" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "mace.png" #optional
credits = "Johsar and Kenzo101" #optional
authors = "Original by johsar(Ported By Kenzo101 Studios)"#optional
description = '''This mod allows you to Elytra-Mace while flying with the elytra!''' #mandatory (Supports multiline text)

[[dependencies.elytramace]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.10)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config="elytramace.forge.mixins.json"

